"use client";

import * as React from "react";
import Box from "@mui/material/Box";
import Card from "@mui/material/Card";
import Grid from "@mui/material/Grid";
import Button from "@mui/material/Button";
import MenuItem from "@mui/material/MenuItem";
import TextField from "@mui/material/TextField";
import Select, { SelectChangeEvent } from "@mui/material/Select";
import InputLabel from "@mui/material/InputLabel";
import FormControl from "@mui/material/FormControl";
import Checkbox from "@mui/material/Checkbox";
import ListItemText from "@mui/material/ListItemText";
import Snackbar from "@mui/material/Snackbar";
import Alert from "@mui/material/Alert";
import { DataGrid, GridColDef } from "@mui/x-data-grid";
import FileDownloadRoundedIcon from "@mui/icons-material/FileDownloadRounded";
import SearchRoundedIcon from "@mui/icons-material/SearchRounded";
import PageHeader from "@/components/common/PageHeader";
import { downloadBlob, reportFileName } from "@/lib/reportExcel";

const ALL_VALUE = "__all__";

export interface FilterOption {
  id: string;
  label: string;
}

interface AppliedFilters {
  selectedIds: string[];
  from: string;
  to: string;
}

/** Whatever a report API returns: the grid only needs an id per row. */
type ReportRow = { id: string | number } & Record<string, unknown>;

interface ApiReportPageProps {
  title: string;
  subtitle: string;
  filterLabel: string;
  /** Plural form for the "All …" summary, when it is not `${filterLabel}s`. */
  filterLabelPlural?: string;
  /**
   * Report API endpoint. Search fetches `{ rows }` from it with the from/to and
   * filter params; Export re-requests it with `export_type=excel`. The filter
   * options come from `${endpoint}/options`.
   */
  endpoint: string;
  /** Query param carrying the selected filter ids. */
  filterParam: string;
  /**
   * True for reports whose figures come from whole-month invoices — the API
   * rejects a range spanning two months, so the hint text says so.
   */
  singleMonth?: boolean;
  columns: GridColDef[];
  exportFileNamePrefix: string;
}

/** `YYYY-MM-DD` for a local date, without the UTC shift `toISOString` applies. */
function toDateInput(date: Date): string {
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${date.getFullYear()}-${month}-${day}`;
}

/**
 * A report page whose rows are generated by a report API: the browser sends the
 * filters and renders what comes back, and Export Excel downloads the workbook
 * the same endpoint builds.
 */
export default function ApiReportPage({
  title,
  subtitle,
  filterLabel,
  filterLabelPlural,
  endpoint,
  filterParam,
  singleMonth,
  columns,
  exportFileNamePrefix,
}: ApiReportPageProps) {
  // The filter defaults to the current month.
  const [from, setFrom] = React.useState(() => {
    const now = new Date();
    return toDateInput(new Date(now.getFullYear(), now.getMonth(), 1));
  });
  const [to, setTo] = React.useState(() => {
    const now = new Date();
    return toDateInput(new Date(now.getFullYear(), now.getMonth() + 1, 0));
  });

  const [filterOptions, setFilterOptions] = React.useState<FilterOption[]>([]);
  const [selectedIds, setSelectedIds] = React.useState<string[]>([]);
  const [rows, setRows] = React.useState<ReportRow[]>([]);
  const [appliedFilters, setAppliedFilters] = React.useState<AppliedFilters | null>(null);
  const [loading, setLoading] = React.useState(false);
  const [exporting, setExporting] = React.useState(false);
  const [toast, setToast] = React.useState<string | null>(null);

  const allLabel = `All ${filterLabelPlural ?? `${filterLabel}s`}`;

  React.useEffect(() => {
    let active = true;
    (async () => {
      try {
        const res = await fetch(`${endpoint}/options`, { cache: "no-store" });
        if (!res.ok) throw new Error("Failed to load filter options.");
        const options = (await res.json()) as FilterOption[];
        if (!active) return;
        setFilterOptions(options);
        setSelectedIds(options.map((o) => o.id));
      } catch {
        if (active) setToast(`Failed to load the ${filterLabel.toLowerCase()} list.`);
      }
    })();
    return () => {
      active = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- the options are fetched once per endpoint
  }, [endpoint]);

  const handleFilterChange = (event: SelectChangeEvent<string[]>) => {
    const value = event.target.value;
    const next = typeof value === "string" ? value.split(",") : value;
    if (next.includes(ALL_VALUE)) {
      setSelectedIds(
        selectedIds.length === filterOptions.length ? [] : filterOptions.map((o) => o.id)
      );
      return;
    }
    setSelectedIds(next);
  };

  /** Selected filters as query params for the report API. */
  const reportQuery = (filters: AppliedFilters): URLSearchParams => {
    const params = new URLSearchParams({ from: filters.from, to: filters.to });
    if (filters.selectedIds.length > 0) params.set(filterParam, filters.selectedIds.join(","));
    return params;
  };

  const errorMessageOf = async (res: Response, fallback: string) => {
    const body = (await res.json().catch(() => null)) as { error?: string } | null;
    return body?.error ?? fallback;
  };

  const handleSearch = async () => {
    const filters: AppliedFilters = { selectedIds, from, to };
    setAppliedFilters(filters);
    setLoading(true);
    try {
      const res = await fetch(`${endpoint}?${reportQuery(filters)}`, { cache: "no-store" });
      if (!res.ok) throw new Error(await errorMessageOf(res, "Failed to generate the report."));
      const data = (await res.json()) as { rows: ReportRow[] };
      setRows(data.rows);
    } catch (error) {
      setRows([]);
      setToast(error instanceof Error ? error.message : "Failed to generate the report.");
    } finally {
      setLoading(false);
    }
  };

  const handleExport = async () => {
    if (!appliedFilters) {
      setToast("Run a search first to load the report before exporting.");
      return;
    }
    setExporting(true);
    try {
      const params = reportQuery(appliedFilters);
      params.set("export_type", "excel");
      const res = await fetch(`${endpoint}?${params}`, { cache: "no-store" });
      if (!res.ok) throw new Error(await errorMessageOf(res, "Failed to export the report."));
      downloadBlob(
        await res.blob(),
        reportFileName(exportFileNamePrefix, `${appliedFilters.from} to ${appliedFilters.to}`)
      );
    } catch (error) {
      setToast(error instanceof Error ? error.message : "Failed to export the report.");
    } finally {
      setExporting(false);
    }
  };

  return (
    <Box>
      <PageHeader
        title={title}
        subtitle={subtitle}
        breadcrumbs={[{ label: "Reports", href: "/reports" }, { label: title }]}
        action={
          <Button
            variant="contained"
            startIcon={<FileDownloadRoundedIcon />}
            onClick={handleExport}
            disabled={exporting}
          >
            {exporting ? "Exporting…" : "Export Excel"}
          </Button>
        }
      />

      <Card sx={{ p: 2, mb: 2 }}>
        <Grid container spacing={2}>
          <Grid size={{ xs: 12, sm: 6, md: 5 }}>
            <FormControl fullWidth size="small">
              <InputLabel id="api-report-filter-label">{filterLabel}</InputLabel>
              <Select
                labelId="api-report-filter-label"
                label={filterLabel}
                multiple
                value={selectedIds}
                onChange={handleFilterChange}
                renderValue={(selected) =>
                  selected.length === filterOptions.length
                    ? allLabel
                    : `${selected.length} selected`
                }
              >
                <MenuItem value={ALL_VALUE}>
                  <Checkbox
                    checked={filterOptions.length > 0 && selectedIds.length === filterOptions.length}
                    indeterminate={
                      selectedIds.length > 0 && selectedIds.length < filterOptions.length
                    }
                  />
                  <ListItemText primary="Select All" />
                </MenuItem>
                {filterOptions.map((option) => (
                  <MenuItem key={option.id} value={option.id}>
                    <Checkbox checked={selectedIds.indexOf(option.id) > -1} />
                    <ListItemText primary={option.label} />
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          </Grid>
          <Grid size={{ xs: 6, sm: 3, md: 3 }}>
            <TextField
              type="date"
              fullWidth
              size="small"
              label="From Date"
              value={from}
              onChange={(e) => setFrom(e.target.value)}
              slotProps={{ inputLabel: { shrink: true } }}
            />
          </Grid>
          <Grid size={{ xs: 6, sm: 3, md: 3 }}>
            <TextField
              type="date"
              fullWidth
              size="small"
              label="To Date"
              value={to}
              onChange={(e) => setTo(e.target.value)}
              slotProps={{ inputLabel: { shrink: true } }}
            />
          </Grid>
          <Grid size={{ xs: 12, sm: 3, md: 1 }}>
            <Button
              variant="contained"
              fullWidth
              startIcon={<SearchRoundedIcon />}
              onClick={handleSearch}
              sx={{ height: 40 }}
            >
              Search
            </Button>
          </Grid>
        </Grid>
      </Card>

      {appliedFilters ? (
        <Card>
          <DataGrid
            autoHeight
            rows={rows}
            columns={columns}
            loading={loading}
            disableRowSelectionOnClick
            initialState={{ pagination: { paginationModel: { pageSize: 10 } } }}
            pageSizeOptions={[10, 25, 50]}
            sx={{ border: "none" }}
          />
        </Card>
      ) : (
        <Card sx={{ p: 4, textAlign: "center", color: "text.secondary" }}>
          Select {filterLabel.toLowerCase()}(s) and a date range
          {singleMonth ? " within one month" : ""}, then click Search to generate the report.
        </Card>
      )}

      <Snackbar open={!!toast} autoHideDuration={4000} onClose={() => setToast(null)}>
        <Alert severity="warning" onClose={() => setToast(null)}>
          {toast}
        </Alert>
      </Snackbar>
    </Box>
  );
}
